name: Deploy to ECR and Elastic Beanstalk

on:
 push:
   branches: [ main ]

jobs:
 deploy:
   runs-on: ubuntu-latest
   
   steps:
   - uses: actions/checkout@v2
   
   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: ap-northeast-2
   
   - name: Login to Amazon ECR
     id: login-ecr
     uses: aws-actions/amazon-ecr-login@v1
   
   - name: Build and push Docker images
     env:
       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
     run: |
       # Backend
       docker build -t $ECR_REGISTRY/community-backend:${{ github.sha }} -f backend/dockerfile ./backend
       docker push $ECR_REGISTRY/community-backend:${{ github.sha }}
       
       # Frontend
       docker build -t $ECR_REGISTRY/community-frontend:${{ github.sha }} -f frontend/dockerfile ./frontend
       docker push $ECR_REGISTRY/community-frontend:${{ github.sha }}
       
   - name: Generate docker-compose.yml
     run: |
       cat > docker-compose.yml << EOL
       version: '3'
       services:
         frontend:
           image: ${{ steps.login-ecr.outputs.registry }}/community-frontend:${{ github.sha }}
           ports:
             - "80:3002"
           mem_limit: 512m
           environment:
             - PORT=3002

         backend:
           image: ${{ steps.login-ecr.outputs.registry }}/community-backend:${{ github.sha }}
           ports:
             - "8080:3003"
           mem_limit: 512m
           environment:
            - PORT=3003
            - AWS_REGION=${{ secrets.AWS_REGION }}
            - AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
            - AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            - AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            - DB_HOST=${{ secrets.DB_HOST }}
            - DB_PORT=${{ secrets.DB_PORT }}
            - DB_USER=${{ secrets.DB_USER }}
            - DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            - DB_NAME=${{ secrets.DB_NAME }}
       EOL
   
   - name: Deploy to Elastic Beanstalk
     uses: einaregilsson/beanstalk-deploy@v21
     with:
       aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       application_name: kakao-community-docker
       environment_name: Kakao-community-docker-env
       version_label: "ver-${{ github.sha }}-${{ github.run_number }}"
       region: ap-northeast-2
       deployment_package: docker-compose.yml
       wait_for_environment_recovery: 300